name: magiCore
version: '1.0-BETA'
main: org.madelineb.magiCore.MagiCore
api-version: '1.19'
authors:
  - madeline
description: Core utils for magi.
commands:
  togglesit:
    description: Toggle the ability to sit on stairs
    usage: /togglesit [global]
    permission: magicore.sit
  placeholderone:
    description: Placeholder command one
    usage: /placeholderone
  placeholdertwo:
    description: Placeholder command two
    usage: /placeholdertwo
  placeholderthree:
    description: Placeholder command three
    usage: /placeholderthree
  bag:
    description: Displays your total gold coins.
    usage: /bag
  givegold:
    description: Gives a player a number of gold coins.
    usage: /givegold
    permission: economy.give
  givesouls:
    description: Give souls to a player.
    usage: /givesouls
    permission: economy.give
  waystone:
    description: Create a waystone at your location
    usage: /waystone <name>
    permission: waystone.create
  waystonetp:
    description: Show available waystones or teleport to one
    usage: /waystonetp <name>
    permission: waystone.use
  shrine:
    description: Create, remove, activate, or list shrines.
    usage: /<command> <create|remove|activate|list> [name]

permissions:
  magicore.sit:
    description: Allows players to toggle sitting functionality
    default: true
  magicore.sit.admin:
    description: Allows admins to toggle global sitting functionality
    default: op
  economy.give:
    description: Allows the player to use /givegold &
  waystone.create:
    description: Allows players to create waystones
    default: op
  waystone.remove:
    description: Allows players to remove waystones
    default: op
  waystone.use:
    description: Allows players to use waystones
    default: true
  shrine.create:
    description: Allows creating shrines
    default: op
  shrine.remove:
    description: Allows removing shrines
    default: op
  shrine.activate:
    description: Allows activating shrines
    default: true